# t-rex configuration

[service.mvt]
viewer = true

[[datasource]]
name = "vapour"
dbconn = "postgresql://vapour:vapour@postgres/vapour"

[grid]
# Predefined grids: web_mercator, wgs84
predefined = "web_mercator"

[[tileset]]
name = "vapour_trail"
attribution = "<a href='http://junglebus.io/'>Jungle Bus</a> <a href='http://www.openstreetmap.org/copyright'>Â© OpenStreetMap contributors</a>"
minzoom = 6
#maxzoom = 22
#center = 0, 0 # longitude, latitude
start_zoom = 10

[[tileset.layer]]
name = "stops"
table_name = "d_stops"
geometry_field = "geom"
geometry_type = "POINT"
srid = 3857
#fid_field = "id"
buffer_size = 0
simplify = true
query_limit = 1000
[[tileset.layer.query]]
minzoom = 11
maxzoom = 13
sql="""
SELECT *
FROM d_stops_cluster
WHERE geom && !bbox!
ORDER BY max_avg_distance
LIMIT 999
"""
[[tileset.layer.query]]
minzoom = 14
sql="""
SELECT *
FROM d_stops
WHERE geom && !bbox!
ORDER BY number_of_routes
LIMIT 999
"""

[[tileset.layer]]
name = "stops_shield"
table_name = "d_stops_shield"
geometry_field = "geom"
geometry_type = "POINT"
srid = 3857
#fid_field = "id"
buffer_size = 0
simplify = true
query_limit = 1000
[[tileset.layer.query]]
minzoom = 14

[[tileset.layer]]
name = "stations"
table_name = "d_stations"
geometry_field = "geom"
geometry_type = "POINT"
srid = 3857
#fid_field = "id"
buffer_size = 0
simplify = true
query_limit = 1000
[[tileset.layer.query]]
minzoom = 6

[[tileset.layer]]
name = "stations_area"
table_name = "d_stations_area"
geometry_field = "geom"
geometry_type = "POLYGON"
srid = 3857
#fid_field = "id"
buffer_size = 1
simplify = true
query_limit = 1000
[[tileset.layer.query]]
minzoom = 13

[[tileset.layer]]
name = "ways"
table_name = "d_ways"
geometry_field = "geom"
geometry_type = "LINESTRING"
srid = 3857
#fid_field = "id"
buffer_size = 2
simplify = true
query_limit = 1000
[[tileset.layer.query]]
minzoom = 11
maxzoom = 12
sql="""
SELECT *
FROM d_ways
WHERE geom && !bbox! AND (max_diameter > 6000 OR number_of_routes > 1)
ORDER BY length DESC
LIMIT 999
"""
[[tileset.layer.query]]
minzoom = 12
sql="""
SELECT *
FROM d_ways
WHERE geom && !bbox!
ORDER BY length DESC
LIMIT 999
"""

[[tileset.layer]]
name = "routes_position"
table_name = "d_routes_position"
geometry_field = "geom"
geometry_type = "POINT"
srid = 3857
#fid_field = "id"
buffer_size = 0
simplify = true
query_limit = 1000
[[tileset.layer.query]]
minzoom = 14

[webserver]
# Bind address. Use 0.0.0.0 to listen on all adresses.
bind = "0.0.0.0"
port = 6767
threads = 4
#cache_control_max_age = 43200

[cache.file]
base = "/srv/mvtcache"
baseurl = "http://example.com/tiles"
